name: Create a Release Tag
on:
  workflow_dispatch:
    inputs:
      version:
        description: new release version
        required: true
        default: (for example, 0.1.0)

jobs:
  ci:
    name: Ensure CI passing
    uses: ./.github/workflows/ci.yaml
  tag:
    needs: [ci]
    runs-on: ubuntu-latest
    - name: Check input
      run: |
        if [[ ! "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo 'version "${{ github.event.inputs.version }}" not in ###.###.### format'
          exit 1
        fi
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/v${{ github.event.inputs.version }}",
            sha: context.sha
          })
